### ISSUE TITLE
Can not compile on Mac OSX 10.6.2 

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#3609]
**_hai_ opened the ticket and wrote:**

> Fails to compile on Mac OSX 10.6.2, reports 
> 
> [SRC] Compiling video/cocoa/fullscreen.mm
> openttd-1.0.0-beta4-source/src/video/cocoa/fullscreen.mm:31:19: error: macos.h: No such file or directory
> 
> 
> Solution:
> Change fullscreen.mm
> 
> from:
> \# include "macos.h"
> 
> to:
> \# include "../../os/macosx/macos.h"
> 
> 

**Reported version**: _1.0.0-beta4_
**Operating system**: _Mac OS X_

---

**Comment by DorpsGek** [comment]
**_Rubidium_ closed the ticket.**

**Reason for closing: _Fixed_**

> a while ago

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/3609_
