### ISSUE TITLE
[OSX] Builds do not run on Mac OS X 10.3.9 anymore

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#4976]
**_segin_ opened the ticket and wrote:**

> OpenTTD 1.1.5 does not run on Mac OS X 10.3.9 (which is listed as compatible on the downloads page)
> 
> Attempting to launch the program from the console shows that the binary  has unresolved symbol references: 
> 
> segin@morgan[22:30]{~}% /Applications/openttd-1.1.5-macosx-universal/OpenTTD.app/Contents/MacOS/openttd
> dyld: /Applications/openttd-1.1.5-macosx-universal/OpenTTD.app/Contents/MacOS/openttd Undefined symbols:
> /Applications/openttd-1.1.5-macosx-universal/OpenTTD.app/Contents/MacOS/openttd undefined reference to _closedir$UNIX2003 expected to be defined in /usr/lib/libSystem.B.dylib
> /Applications/openttd-1.1.5-macosx-universal/OpenTTD.app/Contents/MacOS/openttd undefined reference to _opendir$UNIX2003 expected to be defined in /usr/lib/libSystem.B.dylib
> zsh: trace trap
> segin@morgan[22:31]{~}% uname -a
> Darwin morgan.local 7.9.0 Darwin Kernel Version 7.9.0: Wed Mar 30 20:11:17 PST 2005; root:xnu/xnu-517.12.7.obj~1/RELEASE_PPC  Power Macintosh powerpc
> segin@morgan[22:50]{~}%
> 

**Reported version**: _1.1.5_
**Operating system**: _Mac OS X_

---

**Comment by DorpsGek** [comment]
**_TrueBrain_ wrote:**

> The binaries we compile with OpenTTD are compiled for 10.4+. This means that they will not run on 10.3.
> 
> As far as my memory goes, 10.3 also no longer works, due to some issues in its signal handler. I am not really sure.
> 
> Mac OS X in general is unmaintained atm, as we have no active OSX developer. If you know anyone, or are willing to step up to the job, please drop by our IRC channel, and/or check the open OSX bugs on this bug tracker. The list is rather long, with all kinds of weird (for us) errors and problems.
> 
> That all said, we should document more clearly that our pre-build binaries do not work on 10.3, and possibly document OpenTTD doesn't work on 10.3 at all.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4976#comment10718_

**Comment by DorpsGek** [comment]
**_TrueBrain_ wrote:**

> I was wrong, OpenTTD should run on 10.3.9, if compiled manually. I will look into the compile farm, see if it can compile for 10.3+, instead of 10.4+. The latter is sadly enough unlikely, but I will at least look at it :)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4976#comment10719_

**Comment by DorpsGek** [comment]
**_Rubidium_ wrote:**

> By the looks of it, this must have been broken since somewhere in 2010 or even in 2009. Have you never ran OpenTTD before on that version of OSX, or did you simply never update OpenTTD since then?
> 
> Looking at the resulting files of the compilation it's the ICU library that is causing trouble here.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4976#comment10723_

**Comment by DorpsGek** [comment]
**_Rubidium_ wrote:**

> Does http://devs.openttd.org/~rubidium/openttd-custom-1.1.5-OSX.zip work on 10.3.9?

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4976#comment10724_

**Comment by DorpsGek** [comment]
**_segin_ wrote:**

> I have never ran OpenTTD on Mac OS X before. The only Mac I own is a iMac G3, circa 1998. I mostly use it as a server for small tasks that do not require a lot of RAM/CPU (small MySQL server, Ventrilo, etc.). The download page simply lists the download link as "Mac OS X 10.3-10.5 (universal build)" - I assumed that I could throw it on my old iMac, and have yet another use for a 13 year old computer.
> 
> And yes Remko, that build does in fact work for me! Here's a screenshot as proof: http://img80.imageshack.us/img80/9682/openttd.png

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4976#comment10726_

**Comment by DorpsGek** [comment]
**_Rubidium_ wrote:**

> Nice to see it works. What I did there was remove one of the libraries I suspected to be "wrong".
> 
> Can you try http://devs.openttd.org/~rubidium/openttd-custom-1.1.5v2-OSX.zip which contains a fixed version of the library that was removed in the previous build. Does it still work?

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4976#comment10727_

**Comment by DorpsGek** [comment]
**_segin_ wrote:**

> I'll scp it over and let you know in a little bit. For some reason, my Mac's DNS resolver has ceased to function, yet my SSH and VNC sessions are still fine and dandy.
> 
> By the way, is this truly a 'critical' bug? I mean, Mac OS X 10.3.x is considered obsolete. If OpenTTD is supposed to officially support it (or at least .9, which introduced Tiger's new libstdc++), then I would say 'yes'.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4976#comment10730_

**Comment by DorpsGek** [comment]
**_segin_ wrote:**

> Yes, it works great! Now to figure out how to run OpenTTD as a dedicated server (Wiki, here I come!)
> 
> (And I fixed my DNS resolver issue - the DHCP client went dumb and deleted /etc/resolv.conf, which I quickly recreated by hand.)
> 
> This is why open source is great - it's still possible to get some of today's code to run on 13 year old machines with a little help. 
> 
> Thanks for helping me find yet another use for a machine that has at least two nines availability :)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4976#comment10733_

**Comment by DorpsGek** [comment]
**_segin_ wrote:**

> <Duplicate comment erased... blame Chrome's insistence that refreshing a bug page involves sending a new POSTDATA request.>

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4976#comment10740_

**Comment by DorpsGek** [comment]
**_TrueBrain_ closed the ticket.**

**Reason for closing: _Fixed_**

> 

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4976_

**Comment by DorpsGek** [comment]
**_TrueBrain_ wrote:**

> Official 1.1.5 Mac OS X should now also work under 10.3.9 again. Tnx for the report and testing!

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/4976#comment10753_
