### ISSUE TITLE
Fix build with freetype2 >= 2.5.4

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#6185]
**_AMDmi3_ opened the ticket and wrote:**

> openttd fails to build after update of freetype2 (2.5.3->2.5.4).
> 
> Full log:
> http://beefy1.isc.freebsd.org/data/10i386-quarterly/2014-12-10_14h30m50s/logs/errors/openttd-1.4.2_1.log
> 
> Excerpt:
> \---
> wrkdirs/usr/ports/games/openttd/work/openttd-1.4.2/src/fontcache.cpp:530:15: error: no matching function for call to 'max'
>         int width  = max(1, slot->bitmap.width + (this->fs == FS_NORMAL));
>                      ^~~
> /wrkdirs/usr/ports/games/openttd/work/openttd-1.4.2/src/core/math_func.hpp:38:17: note: candidate template ignored: deduced conflicting types for parameter 'T' ('int' vs. 'unsigned int')
> static inline T max(const T a, const T b)
>                 ^
> /wrkdirs/usr/ports/games/openttd/work/openttd-1.4.2/src/fontcache.cpp:531:15: error: no matching function for call to 'max'
>         int height = max(1, slot->bitmap.rows  + (this->fs == FS_NORMAL));
>                      ^~~
> /wrkdirs/usr/ports/games/openttd/work/openttd-1.4.2/src/core/math_func.hpp:38:17: note: candidate template ignored: deduced conflicting types for parameter 'T' ('int' vs. 'unsigned int')
> static inline T max(const T a, const T b)
>                 ^
> \---
> 
> This happens because FT_Bitmap::rows, FT_Bitmap::width type has changed from int to unsigned int. So, cast both sides (to stay compatible with earlier freetype releases) and the type of resulting variable to unsigned. While here, fix 4 warnings of similar nature.

**Attachments**
- [openttd-fontcache.patch](https://bugs.openttd.org/task/6185/getfile/10051/openttd-fontcache.patch) (1.95 KiB)

**Reported version**: _1.4.4_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_AMDmi3_ wrote:**

> Updated version of a patch, should not produce warnings with older freetype versions.

**Attachments**
- [openttd-fontcache.patch](https://bugs.openttd.org/task/6185/getfile/10052/openttd-fontcache.patch) (2.00 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6185#comment13655_

**Comment by DorpsGek** [comment]
**_planetmaker_ closed the ticket.**

**Reason for closing: _Fixed_**

> In r27079. Thanks for the patch.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/6185_
