### ISSUE TITLE
OpenTTD fails to compile on Mac OS X as of r24488

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#5276]
**_tailcat_ opened the ticket and wrote:**

> OpenTTD fails to compile on Mac OS X 10.8, revision r24487 compiles successfully.
> 
> [SRC] Linking openttd
> Undefined symbols for architecture x86_64:
>   "char const* TryGetBaseSetFile<GraphicsSet>(ContentInfo const*, bool, GraphicsSet const*)", referenced from:
>       ContentInfo::GetTextfile(TextfileType) const   in tcp_content.o
>   "char const* TryGetBaseSetFile<MusicSet>(ContentInfo const*, bool, MusicSet const*)", referenced from:
>       ContentInfo::GetTextfile(TextfileType) const   in tcp_content.o
>   "char const* TryGetBaseSetFile<SoundsSet>(ContentInfo const*, bool, SoundsSet const*)", referenced from:
>       ContentInfo::GetTextfile(TextfileType) const   in tcp_content.o
> ld: symbol(s) not found for architecture x86_64
> collect2: ld returned 1 exit status
> make[1]: *** [openttd] Error 1
> make: *** [all] Error 1
> 
> Bug seems to have been introduced in r24488, it is still won't compile as of r24494

**Reported version**: _trunk_
**Operating system**: _Mac OS X_

---

**Comment by DorpsGek** [comment]
**_planetmaker_ wrote:**

> I fail to reproduce the problem. Can you attach your config.cache? Did you switch architecture or compiler like from gcc 4.0 to gcc 4.2 without re-configure and make clean?

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5276#comment11463_

**Comment by DorpsGek** [comment]
**_tailcat_ wrote:**

> config.cache file attached, yes I did a "make distclean" before I reported the error.

**Attachments**
- [config.cache](https://bugs.openttd.org/task/5276/getfile/8525/config.cache) (1.61 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5276#comment11464_

**Comment by DorpsGek** [comment]
**_frosch_ wrote:**

> Does this diff make it compile again?

**Attachments**
- [fs5276.diff](https://bugs.openttd.org/task/5276/getfile/8526/fs5276.diff) (0.55 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5276#comment11465_

**Comment by DorpsGek** [comment]
**_tailcat_ wrote:**

> Thanks frosch, that solved the problem.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5276#comment11466_

**Comment by DorpsGek** [comment]
**_frosch_ closed the ticket.**

**Reason for closing: _Fixed_**

> in r24496

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/5276_
