### ISSUE TITLE
doesn't compile on Mac OS 10.4 with XCode 2.0

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#2894]
**_fonsinchen_ opened the ticket and wrote:**

> On Mac OS 10.4 with XCode 2.0 kCGBitmapByteOrder32Host isn't defined, which leads to the following compile error:
> 
> [SRC] Compiling video/cocoa/wnd_quartz.mm
> /Users/alve/openttd/src/video/cocoa/wnd_quartz.mm: In function \`void -[OTTD_QuartzView drawRect:](OTTD_QuartzView*, objc_selector*, NSRect)':
> /Users/alve/openttd/src/video/cocoa/wnd_quartz.mm:360: warning: converting to 'uint32' from 'float'
> /Users/alve/openttd/src/video/cocoa/wnd_quartz.mm: In member function \`bool WindowQuartzSubdriver::SetVideoMode(int, int)':
> /Users/alve/openttd/src/video/cocoa/wnd_quartz.mm:498: warning: passing 'float' for converting 3 of 'int Clamp(int, int, int)'
> /Users/alve/openttd/src/video/cocoa/wnd_quartz.mm:501: warning: converting to 'int' from 'float'
> /Users/alve/openttd/src/video/cocoa/wnd_quartz.mm: In member function \`bool WindowQuartzSubdriver::WindowResized()':
> /Users/alve/openttd/src/video/cocoa/wnd_quartz.mm:737: warning: converting to 'int' from 'float'
> /Users/alve/openttd/src/video/cocoa/wnd_quartz.mm:738: warning: converting to 'int' from 'float'
> /Users/alve/openttd/src/video/cocoa/wnd_quartz.mm:752: error: 'kCGBitmapByteOrder32Host' was not declared in this scope
> make[1]: *** [video/cocoa/wnd_quartz.o] Error 1
> make: *** [all] Error 2
> 
> According to the Cairo people kCGBitmapByteOrder32Host can as well be set to 0 in that case (see http://trac.macports.org/ticket/16213). The attached patch does just that. When applied openttd builds and seems to work fine. However, some compile warnings persist:
> 
> [SRC] Compiling video/cocoa/wnd_quartz.mm
> /Users/alve/openttd/src/video/cocoa/wnd_quartz.mm: In function \`void -[OTTD_QuartzView drawRect:](OTTD_QuartzView*, objc_selector*, NSRect)':
> /Users/alve/openttd/src/video/cocoa/wnd_quartz.mm:363: warning: converting to 'uint32' from 'float'
> /Users/alve/openttd/src/video/cocoa/wnd_quartz.mm: In member function \`bool WindowQuartzSubdriver::SetVideoMode(int, int)':
> /Users/alve/openttd/src/video/cocoa/wnd_quartz.mm:501: warning: passing 'float' for converting 3 of 'int Clamp(int, int, int)'
> /Users/alve/openttd/src/video/cocoa/wnd_quartz.mm:504: warning: converting to 'int' from 'float'
> /Users/alve/openttd/src/video/cocoa/wnd_quartz.mm: In member function \`bool WindowQuartzSubdriver::WindowResized()':
> /Users/alve/openttd/src/video/cocoa/wnd_quartz.mm:740: warning: converting to 'int' from 'float'
> /Users/alve/openttd/src/video/cocoa/wnd_quartz.mm:741: warning: converting to 'int' from 'float'
> [SRC] Compiling video/cocoa/wnd_quickdraw.mm
> /Users/alve/openttd/src/video/cocoa/wnd_quickdraw.mm: In member function \`bool WindowQuickdrawSubdriver::SetVideoMode(int, int)':
> /Users/alve/openttd/src/video/cocoa/wnd_quickdraw.mm:427: warning: passing 'float' for converting 3 of 'int Clamp(int, int, int)'
> /Users/alve/openttd/src/video/cocoa/wnd_quickdraw.mm:428: warning: converting to 'int' from 'float'
> /Users/alve/openttd/src/video/cocoa/wnd_quickdraw.mm: In member function \`bool WindowQuickdrawSubdriver::WindowResized()':
> /Users/alve/openttd/src/video/cocoa/wnd_quickdraw.mm:769: warning: converting to 'int' from 'float'
> /Users/alve/openttd/src/video/cocoa/wnd_quickdraw.mm:770: warning: converting to 'int' from 'float'
> /Users/alve/openttd/src/video/cocoa/wnd_quickdraw.mm:773: warning: converting to 'int' from 'float'
> /Users/alve/openttd/src/video/cocoa/wnd_quickdraw.mm:774: warning: converting to 'int' from 'float'

**Attachments**
- [kCGBitmapByteOrder32Host.diff](https://bugs.openttd.org/task/2894/getfile/4289/kCGBitmapByteOrder32Host.diff) (0.34 KiB)

**Reported version**: _0.7.0_
**Operating system**: _All_

---

**Comment by DorpsGek** [comment]
**_Rubidium_ wrote:**

> I think the better fix would be you updating your Xcode. OpenTTD compiles fine with 2.5 and 3.1.2. 
> Don't like to have hacks to support ancient SDKs.
> 
> So I guess you're asking for adding Xcode version detection and disallowing anything < 2.5, right?

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/2894#comment6055_

**Comment by DorpsGek** [comment]
**_fonsinchen_ wrote:**

> Of course that's sort of a hack. Perhaps it should be done somewhere else. I also wouldn't mind it detecting the XCode version and telling me that I have to update (I can apply the hack myself then, as I don't like telling apple about half of my life just to download XCode ... ;)). So ... anything is better than just failing to compile.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/2894#comment6056_

**Comment by DorpsGek** [comment]
**_Rubidium_ closed the ticket.**

**Reason for closing: _Fixed_**

> Kinda; since r16294 it should whine and bail out that you need to install/upgrade XCode 2.5 or higher.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/2894_
