### ISSUE TITLE
[OSX] compile error on MacOS 10.6

### ISSUE THREAD

**Issue by DorpsGek** [OpenTTD/OpenTTD#3190]
**_planetmaker_ opened the ticket and wrote:**

> aeolusreloaded:trunk ingo$ make
> In file included from /Users/ingo/ottd/trunk/src/core/../stdafx.h:16,
>                  from /Users/ingo/ottd/trunk/src/core/alloc_func.cpp:12:
> /Users/ingo/ottd/trunk/src/core/../os/macosx/osx_stdafx.h:30:3: error: # error "Compiling 64 bits without _SQ64 set! (or vice versa)"
> make[1]: *** [alloc_func.o] Error 1
> I couldn't establish where those symbols should have been defined, but I guess in one of the system's libs...
> 
> Compilation is successful, if I remove the check in line 30 in osx_stdafx.h. But that feels like a rather ugly hack.
> 
> Tested with r17495 and gcc 4.2

**Attachments**
- [configure.log](https://bugs.openttd.org/task/3190/getfile/4735/configure.log) (3.01 KiB)

**Reported version**: _trunk_
**Operating system**: _Mac OS X_

---

**Comment by DorpsGek** [comment]
**_Rubidium_ wrote:**

> Oh lovelyl... as expected it fails horribly in the 'real' world where it barely worked with the compile farm.
> 
> For some reason it isn't defining that it *is* a 64 bits compiler, yet it did compile the 64 bits test application as a 64 bits compiler.
> 
> What's extra 'nice' in this is that the headers are littered with those little __LP64__ checks to stop you from building against things like quicktime.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/3190#comment6632_

**Comment by DorpsGek** [comment]
**_Rubidium_ wrote:**

> For those who think that I am going to fix this: no I am not going. All efforts to get something somewhat working with the compile farm ended in something, which broke a compilation at lots of other people, so stuff was done to make their previously working systems compile OpenTTD again. This is just another case where OSX does not behave the same for everyone.
> 
> I do not have the equipment real, virtual or otherwise to give any proper support so the best I can do is not make it worse; I won't be touching it anymore including patches written by others as those have backfired more often than not.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/3190#comment6633_

**Comment by DorpsGek** [comment]
**_planetmaker_ wrote:**

> a query for whether STRGEN is compiled or not also helps and leaves the check otherwise unharmed

**Attachments**
- [make_compile.diff](https://bugs.openttd.org/task/3190/getfile/4809/make_compile.diff) (0.46 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/3190#comment6741_

**Comment by DorpsGek** [comment]
**_planetmaker_ wrote:**

> accidential repost.

**Attachments**
- [make_compile.diff](https://bugs.openttd.org/task/3190/getfile/4810/make_compile.diff) (0.46 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/3190#comment6742_

**Comment by DorpsGek** [comment]
**_planetmaker_ wrote:**

> One of the revisions up to r17717 changed src/video/cocoa/fullscreen.mm and requires some fixes related to the goto jumps in order to compile with gcc 4.2. The solution is to declare all variables prior to the first possible jump. The attached patch fixes that as well as the compile failure in strgen reported above.
> 
> [SRC] Compiling video/cocoa/fullscreen.mm
> /Users/ingo/ottd/trunk/src/video/cocoa/fullscreen.mm: In member function ‘bool FullscreenSubdriver::SetVideoMode(int, int)’:
> /Users/ingo/ottd/trunk/src/video/cocoa/fullscreen.mm:346: error: jump to label ‘ERR_NOT_INDEXED’
> /Users/ingo/ottd/trunk/src/video/cocoa/fullscreen.mm:318: error:   from here
> /Users/ingo/ottd/trunk/src/video/cocoa/fullscreen.mm:337: error:   crosses initialization of ‘NSPoint pt’
> /Users/ingo/ottd/trunk/src/video/cocoa/fullscreen.mm:333: error:   crosses initialization of ‘NSRect screen_rect’
> /Users/ingo/ottd/trunk/src/video/cocoa/fullscreen.mm:349: error: jump to label ‘ERR_DOUBLEBUF’
> /Users/ingo/ottd/trunk/src/video/cocoa/fullscreen.mm:313: error:   from here
> /Users/ingo/ottd/trunk/src/video/cocoa/fullscreen.mm:337: error:   crosses initialization of ‘NSPoint pt’
> /Users/ingo/ottd/trunk/src/video/cocoa/fullscreen.mm:333: error:   crosses initialization of ‘NSRect screen_rect’
> /Users/ingo/ottd/trunk/src/video/cocoa/fullscreen.mm:351: error: jump to label ‘ERR_NO_SWITCH’
> /Users/ingo/ottd/trunk/src/video/cocoa/fullscreen.mm:300: error:   from here
> /Users/ingo/ottd/trunk/src/video/cocoa/fullscreen.mm:337: error:   crosses initialization of ‘NSPoint pt’
> /Users/ingo/ottd/trunk/src/video/cocoa/fullscreen.mm:333: error:   crosses initialization of ‘NSRect screen_rect’
> /Users/ingo/ottd/trunk/src/video/cocoa/fullscreen.mm:353: error: jump to label ‘ERR_NO_CAPTURE’
> /Users/ingo/ottd/trunk/src/video/cocoa/fullscreen.mm:294: error:   from here
> /Users/ingo/ottd/trunk/src/video/cocoa/fullscreen.mm:337: error:   crosses initialization of ‘NSPoint pt’
> /Users/ingo/ottd/trunk/src/video/cocoa/fullscreen.mm:333: error:   crosses initialization of ‘NSRect screen_rect’
> /Users/ingo/ottd/trunk/src/video/cocoa/fullscreen.mm:355: error: jump to label ‘ERR_NO_MATCH’
> /Users/ingo/ottd/trunk/src/video/cocoa/fullscreen.mm:277: error:   from here
> /Users/ingo/ottd/trunk/src/video/cocoa/fullscreen.mm:337: error:   crosses initialization of ‘NSPoint pt’
> /Users/ingo/ottd/trunk/src/video/cocoa/fullscreen.mm:333: error:   crosses initialization of ‘NSRect screen_rect’
> /Users/ingo/ottd/trunk/src/video/cocoa/fullscreen.mm:289: error:   crosses initialization of ‘int gamma_error’
> 

**Attachments**
- [compile_macosx_r17717.diff](https://bugs.openttd.org/task/3190/getfile/4845/compile_macosx_r17717.diff) (2.27 KiB)

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/3190#comment6789_

**Comment by DorpsGek** [comment]
**_michi_cc_ closed the ticket.**

**Reason for closing: _Fixed_**

> In r17767 and r17768.

---
###### _This comment was imported from FlySpray: https://bugs.openttd.org/task/3190_
